export type Release = {
  id: string;
  original_title: string;
  alternative_title: string | null;
  release_year: number | null;
  region: string | null;
  edition: string | null;
  imdb_score: number | null;
  imdb_url: string | null;
  notes: string | null;
  cover_path: string | null;
  thumbnail_path: string | null;
  is_wishlist: boolean;
  cover_url?: string | null;
  thumbnail_url?: string | null;
  overview?: string | null;
  runtime_minutes?: number | null;
  genres?: string[] | null;
  auto_keywords?: string[] | null;
  manual_keywords?: string[] | null;
  keywords_source?: string | null;
  keywords_updated_at?: string | null;
  metadata_provider?: string | null;
  metadata_provider_id?: string | null;
  metadata_last_enriched_at?: string | null;
  metadata_manual_fields?: string[] | null;
  times_suggested?: number | null;
  last_suggested_at?: string | null;
  theme_suggestion_counts?: Record<string, number> | null;
  created_at: string;
  updated_at: string;
};

export type ReleaseInput = {
  original_title: string;
  alternative_title?: string | null;
  release_year?: number | null;
  region?: string | null;
  edition?: string | null;
  imdb_score?: number | null;
  imdb_url?: string | null;
  notes?: string | null;
  cover_path?: string | null;
  thumbnail_path?: string | null;
  overview?: string | null;
  runtime_minutes?: number | null;
  genres?: string[] | null;
  manual_keywords?: string[] | null;
  metadata_provider?: string | null;
  metadata_provider_id?: string | null;
  metadata_manual_fields?: string[] | null;
  is_wishlist?: boolean;
};
